/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uia.SistemaGC.gui;

import cr.ac.uia.SistemaGC.bl.Becados_VW_bl;
import cr.ac.uia.SistemaGC.bl.Becados_bl;
import cr.ac.uia.SistemaGC.entities.Becados;
import cr.ac.uia.SistemaGC.entities.Becados_VW;
import static cr.ac.uia.SistemaGC.gui.Iniciar_Sesion.PUI;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pao
 */
public class Becados_Principal extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarBecas
     */
    public Becados_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmBecas = new javax.swing.JTable();
        lblTituloAdmiBecas = new javax.swing.JLabel();
        btnAsignarBeca = new javax.swing.JButton();
        btnModificarAsignacion = new javax.swing.JButton();
        btnDesasignarBeca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAdmBecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellidos", "Descripción", "Beca", "Porcentaje", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdmBecas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAdmBecas);

        lblTituloAdmiBecas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloAdmiBecas.setText("Administrar Becas");

        btnAsignarBeca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAsignarBeca.setText("Asignar Beca");
        btnAsignarBeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarBecaActionPerformed(evt);
            }
        });

        btnModificarAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificarAsignacion.setText("Modificar Asignación");
        btnModificarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAsignacionActionPerformed(evt);
            }
        });

        btnDesasignarBeca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDesasignarBeca.setText("Desasignar Beca");
        btnDesasignarBeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesasignarBecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnModificarAsignacion)
                        .addGap(53, 53, 53)
                        .addComponent(btnDesasignarBeca)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblTituloAdmiBecas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsignarBeca)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAsignarBeca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTituloAdmiBecas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesasignarBeca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarBecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarBecaActionPerformed
        new Becados_Formulario().setVisible(true);
    }//GEN-LAST:event_btnAsignarBecaActionPerformed

    private void btnModificarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAsignacionActionPerformed
        new Becados_Formulario().setVisible(true);
    }//GEN-LAST:event_btnModificarAsignacionActionPerformed

    private void refreshJTable() {
        try {
            DefaultTableModel tableModel = (DefaultTableModel) tblAdmBecas.getModel();
            tableModel.setRowCount(0); // Limpiando tabla
            Becados_VW_bl bbl = new Becados_VW_bl();
            ArrayList<Becados_VW> al = bbl.select(new Becados_VW());
            for (int i = 0; i < al.size(); i++) {
                Object[] ap
                        = {al.get(i).getCedula(),
                            al.get(i).getNombre(),
                            al.get(i).getApellidos(),
                            al.get(i).getDescripcion(),
                            al.get(i).getBeca(),
                            al.get(i).getPorcentaje(),
                            al.get(i).getActivo()};
                tableModel.addRow(ap);
            }
            this.tblAdmBecas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            this.tblAdmBecas.setModel(tableModel);
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refreshJTable();
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setAutoRequestFocus(true);
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        PUI.setEnabled(true);
        PUI.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void btnDesasignarBecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesasignarBecaActionPerformed
        int i = tblAdmBecas.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this,
                    "Por favor seleccione una celda.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Becados_bl bbl = new Becados_bl();
            Becados b = new Becados();
            b.setId_persona((Integer) tblAdmBecas.getValueAt(i, 0));
            b = bbl.select(b).get(0);
            b.setActivo(!b.getActivo());
            if (bbl.update(b)) {
                refreshJTable();
                JOptionPane.showMessageDialog(this,
                        "Se ha actualizado correctamente la asiganción de beca.",
                        "Correcto",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ha ocurrido un error.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnDesasignarBecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Becados_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Becados_Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarBeca;
    private javax.swing.JButton btnDesasignarBeca;
    private javax.swing.JButton btnModificarAsignacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloAdmiBecas;
    private javax.swing.JTable tblAdmBecas;
    // End of variables declaration//GEN-END:variables
}
