/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uia.SistemaGC.gui;

import cr.ac.uia.SistemaGC.bl.Precio_bl;
import cr.ac.uia.SistemaGC.entities.Precio;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pao
 */
public class GestionParametros extends javax.swing.JFrame {

    /**
     * Creates new form GestionParametros
     */
    public GestionParametros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloGP = new javax.swing.JLabel();
        lblDesayuno = new javax.swing.JLabel();
        lblDesEstudiante = new javax.swing.JLabel();
        lblDesProfesor = new javax.swing.JLabel();
        lblAlmuerzo = new javax.swing.JLabel();
        lblAlmEstudiante = new javax.swing.JLabel();
        lblAlmProfesor = new javax.swing.JLabel();
        btnGuardarParametros = new javax.swing.JButton();
        txtDesEstudiante = new javax.swing.JTextField();
        txtDesProfesor = new javax.swing.JTextField();
        txtAlmEstudiante = new javax.swing.JTextField();
        txtAlmProfesor = new javax.swing.JTextField();
        lblTituloPrecios = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloGP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloGP.setText("Gestionar Parámetros");

        lblDesayuno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDesayuno.setText("Desayuno");

        lblDesEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDesEstudiante.setText("Estudiantes:");

        lblDesProfesor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDesProfesor.setText("Profesores:");

        lblAlmuerzo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlmuerzo.setText("Almuerzo");

        lblAlmEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlmEstudiante.setText("Estudiantes:");

        lblAlmProfesor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlmProfesor.setText("Profesores:");

        btnGuardarParametros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarParametros.setText("Modificar Parámetros");
        btnGuardarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarParametrosActionPerformed(evt);
            }
        });

        txtDesEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtDesEstudiante.setEnabled(false);

        txtDesProfesor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtDesProfesor.setEnabled(false);

        txtAlmEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtAlmEstudiante.setEnabled(false);

        txtAlmProfesor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtAlmProfesor.setEnabled(false);

        lblTituloPrecios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloPrecios.setText("Precios");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("₡");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("₡");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("₡");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("₡");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlmProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAlmEstudiante)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDesProfesor)
                                .addComponent(lblDesEstudiante)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesProfesor)
                    .addComponent(txtDesEstudiante)
                    .addComponent(txtAlmEstudiante, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlmProfesor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarParametros)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloGP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlmuerzo)
                            .addComponent(lblDesayuno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblTituloPrecios)))
                .addGap(82, 162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloGP)
                .addGap(16, 16, 16)
                .addComponent(lblTituloPrecios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDesayuno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesEstudiante)
                    .addComponent(txtDesEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesProfesor)
                    .addComponent(txtDesProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(lblAlmuerzo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlmEstudiante)
                    .addComponent(txtAlmEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlmProfesor)
                    .addComponent(txtAlmProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarParametrosActionPerformed
        try {
            txtAlmEstudiante.setEnabled(true);
            txtAlmProfesor.setEnabled(true);
            txtDesEstudiante.setEnabled(true);
            txtDesProfesor.setEnabled(true);
            btnGuardarParametros.setText("Guardar Parámetros");
            //UPDATE
            Precio Aest = new Precio();
            Precio Dest = new Precio();
            Precio Aprf = new Precio();
            Precio Dprf = new Precio();
            Dest.setId_comida(1);
            Dprf.setId_comida(1);
            Aest.setId_comida(2);
            Aprf.setId_comida(2);
            Dest.setId_persona(1);
            Aest.setId_persona(1);
            Dprf.setId_persona(2);
            Aprf.setId_persona(2);
            Precio_bl bl = new Precio_bl();
            if(bl.update(Dprf)&& bl.update(Aprf)&& bl.update(Dest)&& bl.update(Aest)){
                JOptionPane.showMessageDialog(null, "Parámetros modificados correctamente", 
                        "Gestión de Parámetros", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Se produjo un error, ingrese los datos nuevamente.", 
                        "Gestión de Parámetros", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionParametros.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
     
    }//GEN-LAST:event_btnGuardarParametrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarParametros;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAlmEstudiante;
    private javax.swing.JLabel lblAlmProfesor;
    private javax.swing.JLabel lblAlmuerzo;
    private javax.swing.JLabel lblDesEstudiante;
    private javax.swing.JLabel lblDesProfesor;
    private javax.swing.JLabel lblDesayuno;
    private javax.swing.JLabel lblTituloGP;
    private javax.swing.JLabel lblTituloPrecios;
    private javax.swing.JTextField txtAlmEstudiante;
    private javax.swing.JTextField txtAlmProfesor;
    private javax.swing.JTextField txtDesEstudiante;
    private javax.swing.JTextField txtDesProfesor;
    // End of variables declaration//GEN-END:variables
}
