/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uia.SistemaGC.gui;

import cr.ac.uia.SistemaGC.bl.Personas_VW_bl;
import cr.ac.uia.SistemaGC.bl.Personas_bl;
import cr.ac.uia.SistemaGC.entities.Personas;
import cr.ac.uia.SistemaGC.entities.Personas_VW;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pao
 */
public class Personas_Principal extends SGCForm {

    /**
     * Creates new form Personas
     */
    public Personas_Principal() throws ClassNotFoundException {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        lblTituloGP = new javax.swing.JLabel();
        btnAgregarPersona = new SGCButton();
        btnModificarPersona = new SGCButton();
        btnDesactivarPersona = new SGCButton();
        btnImprimirCodigo = new SGCButton();
        jLabel1 = new javax.swing.JLabel();
        txtFiltro = new SGCTextField();
        lblFiltro = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblPersonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Apellidos", "Fecha de Nacimiento", "Celular", "Teléfono", "Encargado", "Activo", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersonas.setShowHorizontalLines(false);
        tblPersonas.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblPersonas);

        lblTituloGP.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloGP.setText("Gestión de Personas");

        btnAgregarPersona.setText("Agregar Persona");
        btnAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonaActionPerformed(evt);
            }
        });

        btnModificarPersona.setText("Modificar Persona");
        btnModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonaActionPerformed(evt);
            }
        });

        btnDesactivarPersona.setLabel("Des/activar Persona");
        btnDesactivarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarPersonaActionPerformed(evt);
            }
        });

        btnImprimirCodigo.setText("Imprimir Código de Barra");
        btnImprimirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCodigoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/uia/SistemaGC/img/persons.png"))); // NOI18N

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        lblFiltro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFiltro.setText("Búsqueda por nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnModificarPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                        .addComponent(btnDesactivarPersona)
                        .addGap(166, 166, 166)
                        .addComponent(btnImprimirCodigo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFiltro)
                                .addGap(18, 18, 18)
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTituloGP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarPersona)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblTituloGP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFiltro))))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregarPersona)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarPersona)
                    .addComponent(btnImprimirCodigo)
                    .addComponent(btnDesactivarPersona))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonaActionPerformed
        this.setVisible(false);
        new Personas_Formulario().setVisible(true);
    }//GEN-LAST:event_btnAgregarPersonaActionPerformed

    private void btnModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonaActionPerformed
        int i = tblPersonas.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this,
                    "Por favor seleccione una celda.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        new Personas_Formulario(true,
                new Personas(
                        (Long) tblPersonas.getValueAt(i, 0),
                        (String) tblPersonas.getValueAt(i, 1),
                        (String) tblPersonas.getValueAt(i, 2),
                        (java.util.Date) tblPersonas.getValueAt(i, 3),
                        (Integer) tblPersonas.getValueAt(i, 4),
                        (Integer) tblPersonas.getValueAt(i, 5),
                        (String) tblPersonas.getValueAt(i, 6),
                        (Boolean) tblPersonas.getValueAt(i, 7),
                        (Integer) tblPersonas.getValueAt(i, 8))).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModificarPersonaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Iniciar_Sesion.activarPrincipal();
    }//GEN-LAST:event_formWindowClosed

    private void btnImprimirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCodigoActionPerformed
        int i = tblPersonas.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this,
                    "Por favor seleccione una celda.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            new BarCode_Formulario((Long) tblPersonas.getValueAt(i, 0)).setVisible(true);
        }
    }//GEN-LAST:event_btnImprimirCodigoActionPerformed

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        // Busqueda por nombre
        new SGCFiltro().Filtrar(txtFiltro, tblPersonas);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        txtFiltro.setText(txtFiltro.getText().toUpperCase());
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void btnDesactivarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarPersonaActionPerformed
        int i = tblPersonas.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this,
                    "Por favor seleccione una persona en la tabla.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Personas_bl pbl = new Personas_bl();
            Personas p = new Personas();
            p.setCedula(Long.parseLong(tblPersonas.getValueAt(i, 0).toString()));
            p = pbl.select(p).get(0);
            p.setActivo(!p.getActivo());
            if (pbl.update(p)) {
                refreshTable();
                JOptionPane.showMessageDialog(this,
                        "Se ha actualizado correctamente la asiganción de beca.",
                        "Correcto",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ha ocurrido un error.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }        
    }//GEN-LAST:event_btnDesactivarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personas_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Personas_Principal().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Personas_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersona;
    private javax.swing.JButton btnDesactivarPersona;
    private javax.swing.JButton btnImprimirCodigo;
    private javax.swing.JButton btnModificarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblTituloGP;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() throws ClassNotFoundException {
        try {
            DefaultTableModel tableModel = (DefaultTableModel) tblPersonas.getModel();
            tableModel.setRowCount(0);
            TableRowSorter<TableModel> order = new TableRowSorter<>(tableModel);
            tblPersonas.setRowSorter(order);
            Personas_VW_bl pbl = new Personas_VW_bl();
            ArrayList<Personas_VW> al = pbl.select(new Personas_VW());
            for (int i = 0; i < al.size(); i++) {
                Object[] ap = {al.get(i).getCedula(),
                    al.get(i).getNombre(),
                    al.get(i).getApellidos(),
                    al.get(i).getFecha_nacimiento(),
                    al.get(i).getTel_celular(),
                    al.get(i).getTel_habitacion(),
                    al.get(i).getEncargado(),
                    al.get(i).getActivo(),
                    al.get(i).getDescripcion()};
                tableModel.addRow(ap);
            }
            this.tblPersonas.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
         System.err.println(e.getClass().getName()+": "+e.getMessage());
         System.exit(0);
        }
    }
}


