/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uia.SistemaGC.ui;

/**
 *
 * @author Pao
 */
public class AgregarPersona extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPersona
     */
    public AgregarPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoPersona = new javax.swing.ButtonGroup();
        RBEstudiante = new javax.swing.JRadioButton();
        RBProfesor = new javax.swing.JRadioButton();
        lblCedulaPersona = new javax.swing.JLabel();
        lblNombrePersona = new javax.swing.JLabel();
        lblApellidosPersona = new javax.swing.JLabel();
        lblFechaPersona = new javax.swing.JLabel();
        lblTelefonosPersona = new javax.swing.JLabel();
        lblContactoPersona = new javax.swing.JLabel();
        lblObservacionesPersona = new javax.swing.JLabel();
        btnGuardarPersona = new javax.swing.JButton();
        txtCedulaPersona = new javax.swing.JTextField();
        txtNombrePersona = new javax.swing.JTextField();
        txtApellidosPersona = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        txtTelefono2 = new javax.swing.JTextField();
        txtContactoPersona = new javax.swing.JTextField();
        txtObservacionesPersona = new javax.swing.JTextField();
        txtFechaPersona = new javax.swing.JFormattedTextField();
        lblTituloAgPersona = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TipoPersona.add(RBEstudiante);
        RBEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RBEstudiante.setText("Estudiante");

        TipoPersona.add(RBProfesor);
        RBProfesor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RBProfesor.setText("Profesor");

        lblCedulaPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedulaPersona.setText("Cédula:");

        lblNombrePersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombrePersona.setText("Nombre:");

        lblApellidosPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApellidosPersona.setText("Apellidos:");

        lblFechaPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaPersona.setText("Fecha de Nacimiento:");

        lblTelefonosPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefonosPersona.setText("Teléfonos:");

        lblContactoPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContactoPersona.setText("Persona para contacto:");

        lblObservacionesPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObservacionesPersona.setText("Observaciones:");

        btnGuardarPersona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarPersona.setText("Guardar Persona");

        txtFechaPersona.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblTituloAgPersona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAgPersona.setText("Gestión de Personas");

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Cargar Foto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellidosPersona)
                        .addGap(123, 123, 123)
                        .addComponent(txtApellidosPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaPersona)
                        .addGap(51, 51, 51)
                        .addComponent(txtFechaPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefonosPersona)
                        .addGap(120, 120, 120)
                        .addComponent(txtTelefono1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContactoPersona)
                        .addGap(41, 41, 41)
                        .addComponent(txtContactoPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(txtTelefono2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObservacionesPersona)
                        .addGap(89, 89, 89)
                        .addComponent(txtObservacionesPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnGuardarPersona)
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombrePersona)
                            .addComponent(lblCedulaPersona))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaPersona)
                            .addComponent(txtNombrePersona))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBEstudiante)
                    .addComponent(RBProfesor))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloAgPersona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(RBEstudiante)
                        .addGap(42, 42, 42)
                        .addComponent(RBProfesor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTituloAgPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaPersona)
                    .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePersona)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPersona)
                    .addComponent(txtApellidosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPersona)
                    .addComponent(txtFechaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonosPersona)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactoPersona)
                    .addComponent(txtContactoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacionesPersona)
                    .addComponent(txtObservacionesPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnGuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBEstudiante;
    private javax.swing.JRadioButton RBProfesor;
    private javax.swing.ButtonGroup TipoPersona;
    private javax.swing.JButton btnGuardarPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidosPersona;
    private javax.swing.JLabel lblCedulaPersona;
    private javax.swing.JLabel lblContactoPersona;
    private javax.swing.JLabel lblFechaPersona;
    private javax.swing.JLabel lblNombrePersona;
    private javax.swing.JLabel lblObservacionesPersona;
    private javax.swing.JLabel lblTelefonosPersona;
    private javax.swing.JLabel lblTituloAgPersona;
    private javax.swing.JTextField txtApellidosPersona;
    private javax.swing.JTextField txtCedulaPersona;
    private javax.swing.JTextField txtContactoPersona;
    private javax.swing.JFormattedTextField txtFechaPersona;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtObservacionesPersona;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
